package webdriver;

import org.testng.annotations.Test;
import org.testng.annotations.BeforeClass;

import java.util.Random;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.AfterClass;

public class Topic_21_JavaScript_Executor {

	WebDriver driver;
	JavascriptExecutor jsExecutor;
	WebElement element;
	String email, cName, cDOB, cAddress, cCity, cState, cPin, cMobile, cEmail, cPassword, cID;
	By txtName = By.name("name");
	By txtGender = By.name("gender");
	By txtDOB = By.name("dob");
	By txtAddress = By.name("addr");
	By txtCity = By.name("city");
	By txtState = By.name("state");
	By txtPin = By.name("pinno");
	By txtMobile = By.name("telephoneno");
	By txtEmail = By.name("emailid");
	By txtPassword = By.name("password");
	
	@BeforeClass
	public void beforeClass() {
		//driver = new FirefoxDriver();
		System.setProperty("webdriver.chrome.driver", "./Browser-Drivers/chromedriver.exe");
		driver = new ChromeDriver();
		jsExecutor= (JavascriptExecutor)driver;
		driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		driver.manage().window().maximize();
		email = "diep.nguyen" + getRandomNum() + "@gmail.com";
		cName = "Kim Nguyen";
		cDOB = "1987-12-18";
		cAddress = "no 1 Nguyen Truong To street";
		cCity = "Hochiminh";
		cState = "Ho Chi Minh";
		cPin = "111222";
		cMobile = "0125369897";
		cEmail = email;
		cPassword = "123456";
	}
	

	public void TC_01_JavaScript_Executor() {
		//Open the app under test
		driver.get("http://live.demoguru99.com/");
		
		//get domain by JE
		String domain = (String)executeForBrowser("return document.domain");
		Assert.assertEquals(domain, "live.demoguru99.com");
		
		//get url by JE
		String currentURL = (String)executeForBrowser("return document.URL");
		Assert.assertEquals(currentURL, "http://live.demoguru99.com/");
		
		//Click on Mobile by JE
		clickToElementByJS("//a[text()='Mobile']");
		
		//Select 'Add to Cart' of Samsung Galaxy
		clickToElementByJS("//a[@title='Samsung Galaxy']/parent::h2/following-sibling::div[@class='actions']//span[text()='Add to Cart']");
		
		//Verify message 'Samsung Galaxy was added to your shopping cart.' display
		verifyTextInInnerText("Samsung Galaxy was added to your shopping cart.");
			
		//Click on 'Customer Service'
		clickToElementByJS("//a[text()='Customer Service']");
		
		//get title of Customer Service page
		String title = (String) executeForBrowser("return document.title");
		
		//Verify title of Customer Service page = 'Customer Service'
		Assert.assertEquals(title, "Customer Service");
		
		//Scroll to Newsletter field
		scrollToElement("//input[@id='newsletter']");
		
		//Verify 'Praesent ipsum libero, auctor ac, tempus nec, tempor nec, justo' display
		verifyTextInInnerText("Praesent ipsum libero, auctor ac, tempus nec, tempor nec, justo");
		
		//Navigate to http://demo.guru99.com/v4/ by JE
		navigateToUrlByJS("http://demo.guru99.com/v4/");
		
		//Verify domain = 'demo.guru99.com'
		domain =(String) executeForBrowser("return document.domain");
		Assert.assertEquals(domain, "demo.guru99.com");
	}
	
	public void TC_02_Remove_Attribute_BY_JE() {
		//Open the app under test
		driver.get("http://demo.guru99.com/v4");
		
		String loginURL = driver.getCurrentUrl();
		driver.findElement(By.xpath("//a[text()='here']")).click();

		// Entering your email
		driver.findElement(By.name("emailid")).sendKeys(email);
		driver.findElement(By.name("btnLogin")).click();

		// get userid and password are generated by the email entered before
		String userID = driver.findElement(By.xpath("//td[text()='User ID :']/following-sibling::td")).getText();
		String password = driver.findElement(By.xpath("//td[text()='Password :']/following-sibling::td")).getText();

		// get back to login page
		driver.get(loginURL);

		// login with userID and password
		driver.findElement(By.name("uid")).sendKeys(userID);
		driver.findElement(By.name("password")).sendKeys(password);
		driver.findElement(By.name("btnLogin")).click();
		
		// verify homepage is displayed
		Assert.assertTrue(driver.findElement(By.xpath("//td[contains(text()," + userID + ")]")).isDisplayed());

		// Select New Customer
		driver.findElement(By.xpath("//a[text()='New Customer']")).click();

		// Enter customer infos
		driver.findElement(txtName).sendKeys(cName);
		
		//remove attribute type of DOB field
		removeAttributeInDOM("//input[@name='dob']", "type");
		
		driver.findElement(txtDOB).sendKeys(cDOB);
		driver.findElement(txtAddress).sendKeys(cAddress);
		driver.findElement(txtCity).sendKeys(cCity);
		driver.findElement(txtState).sendKeys(cState);
		driver.findElement(txtPin).sendKeys(cPin);
		driver.findElement(txtMobile).sendKeys(cMobile);
		driver.findElement(txtEmail).sendKeys(email);
		driver.findElement(txtPassword).sendKeys(cPassword);
		driver.findElement(By.name("sub")).click();
		
		//verify create new customer successfully
		Assert.assertTrue(driver.findElement(By.xpath("//p[text()='Customer Registered Successfully!!!']")).isDisplayed());
	}
	
	@Test
	public void TC_03_Create_Account() {
		//Open the app under test
		driver.get("http://live.demoguru99.com/");
		
		//Click 'My Account' on header
		clickToElementByJS("//div[@id='header-account']//a[text()='My Account']");
		
		//Click 'Create An Acccount'
		clickToElementByJS("//a[@title='Create an Account']");
		
		//Enter first name
		String firstName = "//input[@id='firstname']";
		String lastName = "//input[@id='lastname']";
		String userEmail = "//input[@id='email_address']";
		String password = "//input[@id='password']";
		String confirmPassword = "//input[@id='confirmation']";
		
		
		highlightElement(firstName);
		driver.findElement(By.xpath(firstName)).sendKeys("Van");
		
		highlightElement(lastName);
		driver.findElement(By.xpath(lastName)).sendKeys("Tran");
		
		highlightElement(userEmail);
		email = "van.tran" + getRandomNum() + "@gmail.com";
		driver.findElement(By.xpath(userEmail)).sendKeys(email);
		
		highlightElement(password);
		driver.findElement(By.xpath(password)).sendKeys(cPassword);
		
		highlightElement(confirmPassword);
		driver.findElement(By.xpath(confirmPassword)).sendKeys(cPassword);
		
		//Click on button 'Register'
		clickToElementByJS("//button[@title='Register']");
		
		//Verify message 'Thank you for registering with Main Website Store.' display
		verifyTextInInnerText("Thank you for registering with Main Website Store.");
		
		//Logout
		clickToElementByJS("//a[@title='Log Out']");
		
		//sleepInSecond(6);
		//Verify user back to homepage after logout successfully
		Assert.assertTrue(driver.findElement(By.xpath("//h2[contains(text(),'This is demo site for')]")).isDisplayed());
		driver.findElement(By.xpath("")).is
	}
	
	// Browser
	public Object executeForBrowser(String javaSript) {
		return jsExecutor.executeScript(javaSript);
	}

	public boolean verifyTextInInnerText(String textExpected) {
		String textActual = (String) jsExecutor.executeScript("return document.documentElement.innerText.match('" + textExpected + "')[0]");
		System.out.println("Text actual = " + textActual);
		return textActual.equals(textExpected);
	}

	public void scrollToBottomPage() {
		jsExecutor.executeScript("window.scrollBy(0,document.body.scrollHeight)");
	}

	public void navigateToUrlByJS(String url) {
			jsExecutor.executeScript("window.location = '" + url + "'");
		}

	// Element
	public void highlightElement(String locator) {
		element = driver.findElement(By.xpath(locator));
		String originalStyle = element.getAttribute("style");
		jsExecutor.executeScript("arguments[0].setAttribute(arguments[1], arguments[2])", element, "style", "border: 5px solid red; border-style: dashed;");
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		jsExecutor.executeScript("arguments[0].setAttribute(arguments[1], arguments[2])", element, "style", originalStyle);

	}

	public void clickToElementByJS(String locator) {
		element = driver.findElement(By.xpath(locator));
		jsExecutor.executeScript("arguments[0].click();", element);
	}

	public void scrollToElement(String locator) {
		element = driver.findElement(By.xpath(locator));
		jsExecutor.executeScript("arguments[0].scrollIntoView(true);", element);
	}

	public void sendkeyToElementByJS(String locator, String value) {
		element = driver.findElement(By.xpath(locator));
		jsExecutor.executeScript("arguments[0].setAttribute('value', '" + value + "')", element);
	}

	public void removeAttributeInDOM(String locator, String attributeRemove) {
		element = driver.findElement(By.xpath(locator));
		jsExecutor.executeScript("arguments[0].removeAttribute('" + attributeRemove + "');", element);
	}
	
	private void sleepInSecond(long timeout) {
		try {
			Thread.sleep(timeout*1000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	private int getRandomNum() {
		Random random = new Random();
		return random.nextInt(999999);
	}

	
	@AfterClass
	public void afterClass() {
		//driver.quit();
	}
}
